[workspace]
members = [
 "wgpu-jumpstart",
 "whstlrs",
]

resolver="2"

[workspace.dependencies]
wgpu = "0.20"
bytemuck = { version = "1.5", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
futures = "0.3"

wgpu-jumpstart = { path = "./wgpu-jumpstart" }